image: node:8.12.0
clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - npm install -g @angular/cli
          - npm install
          - ng build --prod
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master