version: 2
jobs:
  build:
    working_directory: ~/opsonion-web
    docker:
      - image: node:8.12.0
    steps:
      - checkout
      - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install -g @angular/cli
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Deploy to Heroku
          command: |
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
            fi